config/routes.rb
Rails.application.routes.draw do
  # delete "list/:id", to: "list#destroy", as: :delete_list
  resources :lists do
    resources :bookmarks, only: [:new, :create, :show]
  end
  resources :bookmarks, only: [:destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :overview, presence: true
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
before_action :set_list, except: [:destroy]

  def new
    @bookmark = Bookmark.new
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to @bookmark.list
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to @list
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<br>
<div class="container">
<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>
<br>
<br>
<%= link_to("Volver a las listas", lists_path) %>
</div>

app/views/bookmarks/show.html.erb
<h1><%= @bookmark.comment %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="jumbotron jumbotron-fluid">

  <h1 class="display-4">Mis listas de peliculas</h1>

</div>
<div class="container2">
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4 mb-4">
        <div class="cards">
          <div class="card-category" style='background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path "card.png" %>)'>
            <%= link_to list.name, list_path(list), style: "text-decoration: none; color: inherit" %>
          </div>
        </div>
    </div>
    <% end %>
  </div>
  <%= link_to("Nueva Lista", new_list_path) %>
</div>

app/views/lists/new.html.erb
<br>
<div class="container">
<%= simple_form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>
<br>
<br>
<%= link_to("Volver a las listas", lists_path) %>
</div>

app/views/lists/show.html.erb
<header class="navbar">
  <%= link_to "Inicio", root_path, class: "navbar__link" %>
  <%= link_to "Mis listas", lists_path, class: "navbar__link" %>
  <h6>🎞 Mis listas de peliculas 🎞</h6>
  <%= link_to "Agregar Pelicula", new_list_bookmark_path(@list), class: "navbar__link" %>
  <%= link_to "Eliminar lista", list_path(@list), method: :delete, data: { confirm: "Estás seguro?" }, class: "navbar__link" %>
</header>

<div class="banner" style="background-image:  url('<%= cl_image_path @list.photo.key, height: 300, width: 400, crop: :fill if @list.photo.attached? %>')">
  <h1><%= @list.name %></h1>
</div>


<ul class="cards">
  <% @list.movies.each do |movie| %>
    <li class="cards__item">
      <div class="card">
        <div><img src= <%= movie.poster_url %> /></div>
        <div class="card__content">
          <div class="card__title"><%= movie.title %></div>
          <p class="card__text"><%= movie.overview %></p>
          <% movie.bookmarks.where(list: @list).each do |bookmark| %>
          <button class="btn btn--block card__btn"><%= link_to "ELIMINAR PELICULA DE LA LISTA", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Seguro que quiere remover #{movie.title} de su lista #{@list.name}"} %></button>
          <p class="card__text"> Comentario: <%= bookmark.comment %> </p>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>